import yaml

with open("typo-map.yaml", 'r') as f: typo_map = yaml.safe_load(f)

a = typo_map['a']
b = typo_map['b']
c = typo_map['c']
d = typo_map['d']
e = typo_map['e']
f = typo_map['f']
g = typo_map['g']
h = typo_map['h']
i = typo_map['i']
j = typo_map['j']
k = typo_map['k']
l = typo_map['l']
m = typo_map['m']
n = typo_map['m']
o = typo_map['o']
p = typo_map['p']
q = typo_map['q']
r = typo_map['r']
s = typo_map['s']
t = typo_map['t']
u = typo_map['u']
v = typo_map['v']
w = typo_map['w']
x = typo_map['x']
y = typo_map['y']
z = typo_map['z']
